application: hangout-apps
version: 1
runtime: python27
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: .*
  script: main.py

libraries:
- name: jinja2
  version: latest